name: Build and Push Docker image to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:  # permite acionar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # necessário para push no GHCR

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configurar nome da imagem
      id: meta
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/subdomain-redirect
        echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Build da imagem
      run: |
        docker build -t ${{ steps.meta.outputs.image_name }} .

    - name: Push da imagem para GHCR
      run: |
        docker push ${{ steps.meta.outputs.image_name }}
